<template>
  <div>
    <div>
      <span>3C</span>
      <ul>
        品牌旗艦
        <li>SanDisk</li>
        <li>Seagate</li>
        <li>TP-Link</li>
        <li>創見</li>
        <li>三星儲存</li>
      </ul>
      <ul>
        相關分類
        <li>筆記電腦</li>
        <li>桌上電腦</li>
        <li>商用電腦</li>
        <li>DIY電腦</li>
        <li>LCD電腦</li>
        <li>電競螢幕</li>
        <li>網路</li>
        <li>視訊監控</li>
        <li>SSD</li>
        <li>外接硬碟/SSD</li>
        <li>內接硬碟</li>
        <li>網路硬碟</li>
        <li>CPU</li>
        <li>主機板</li>
        <li>顯示卡</li>
        <li>電源供應器</li>
        <li>電腦機殼</li>
        <li>記憶體</li>
        <li>記憶卡</li>
        <li>隨身碟</li>
        <li>UPS</li>
        <li>電腦擴充</li>
        <li>軟體</li>
        <li>耗材</li>
        <li>線材</li>
        <li>電競專區</li>
        <li>台灣精品</li>
        <li>企業專區</li>
        <li>清倉</li>
        <li>南紡3C</li>
        <li>露天</li>
      </ul>
      <span>所有3C</span>
    </div>
    <div>
      <span>周邊</span>
      <ul>
        品牌旗艦
        <li>Logitech/羅技</li>
        <li>Razer雷蛇</li>
        <li>HyperX</li>
        <li>微軟Office</li>
        <li>Marshall</li>
      </ul>
      <ul>
        相關分類
        <li>滑鼠</li>
        <li>鍵盤</li>
        <li>喇叭</li>
        <li>耳機/麥克風</li>
        <li>直播設備</li>
        <li>線材</li>
        <li>延長線</li>
        <li>USBHUB/周邊</li>
        <li>電競椅</li>
        <li>辦公椅</li>
        <li>手寫/繪圖板</li>
        <li>閱讀器</li>
        <li>電腦軟體</li>
        <li>下載/點數</li>
        <li>辦公設備</li>
        <li>營業設備</li>
        <li>辦公傢俱</li>
        <li>噴墨印表機</li>
        <li>雷射印表機</li>
        <li>墨水匣/標籤帶</li>
        <li>碳粉匣</li>
        <li>紙類</li>
        <li>商用列印</li>
        <li>充電/電池</li>
        <li>筆電周邊/配件</li>
        <li>光碟片/機</li>
        <li>三井3C</li>
        <li>電腦/商務包</li>
        <li>嚴選小舖</li>
      </ul>
      <span>所有周邊</span>
    </div>
    <div>
      <span>NB</span>
      <ul>
        品牌旗艦
        <li>Intel第13&12代</li>
        <li>筆記電腦</li>
        <li>ASUS華碩</li>
        <li>ACER宏碁</li>
        <li>HP惠普</li>
        <li>Lenovo聯想</li>
        <li>微軟Surface</li>
        <li>DELL戴爾</li>
        <li>其他品牌</li>
        <li>APPLE</li>
        <li>ASUSZenBook</li>
        <li>ThinkPad商務</li>
        <li>ROG潮流電競</li>
        <li>MSI微星電競</li>
        <li>技嘉電競</li>
        <li>RAZER電競</li>
        <li>HP電競</li>
        <li>LEGION電競</li>
      </ul>
      <ul>
        相關分類
        <li>特仕筆電</li>
        <li>商用筆電</li>
        <li>EVO輕薄筆電</li>
        <li>2in1/觸控筆電</li>
        <li>電競筆電</li>
        <li>NVIDIA創作專區</li>
        <li>MSI微星</li>
        <li>Mac周邊</li>
      </ul>
    </div>
    <div>
      <span>通訊</span>
      <ul>
        品牌旗艦
        <li>APPLE</li>
        <li>三星旗艦</li>
        <li>Android</li>
        <li>Google</li>
        <li>小米</li>
        <li>realme</li>
        <li>Jabra</li>
        <li>鐵三角</li>
        <li>Sennheiser</li>
        <li>UAG</li>
        <li>犀牛盾</li>
        <li>魚骨牌</li>
        <li>惡魔殼</li>
        <li>OtterBox</li>
        <li>imos</li>
        <li>大通</li>
        <li>綠聯</li>
        <li>Belkin</li>
      </ul>
      <ul>
        相關分類
        <li>智慧手機</li>
        <li>POCO</li>
        <li>OPPO</li>
        <li>vivo</li>
        <li>華為</li>
        <li>平板</li>
        <li>一般手機</li>
        <li>福利品</li>
        <li>藍芽耳機</li>
        <li>智慧穿戴</li>
        <li>手機平板配件</li>
        <li>氮化鎵</li>
        <li>APPLE周邊</li>
        <li>安卓殼套</li>
        <li>iPhone殼套</li>
        <li>安卓保貼</li>
        <li>Qi/行電</li>
        <li>線材</li>
        <li>充電/傳輸</li>
        <li>旅遊卡</li>
        <li>支架</li>
        <li>備份</li>
      </ul>
    </div>
    <div>
      <span>數位</span>
      <ul>
        品牌旗艦
        <li>Bose旗艦館</li>
        <li>Nitendo</li>
        <li>PlayStation</li>
        <li>Xbox</li>
        <li>GoPrp</li>
        <li>DJI旗艦館</li>
        <li>SONY</li>
        <li>Nikon旗艦館</li>
        <li>CANON</li>
        <li>Jabra</li>
        <li>鐵三角</li>
        <li>森海塞爾耳機</li>
      </ul>
      <ul>
        <li>電玩/遊戲</li>
        <li>遊戲配件/周邊</li>
        <li>藍芽耳機</li>
        <li>智慧穿戴</li>
        <li>運動/攝影機</li>
        <li>空拍機</li>
        <li>數位相機</li>
        <li>相機鏡頭</li>
        <li>微單眼</li>
        <li>單眼相機</li>
        <li>鏡頭濾鏡</li>
        <li>防潮箱</li>
        <li>攝錄影器材</li>
        <li>相機專業配件</li>
        <li>攝影腳架</li>
        <li>攝影包</li>
        <li>錄音/音訊周邊</li>
        <li>相機電池</li>
        <li>閱讀器</li>
      </ul>
    </div>
    <div>
      <span>家電</span>
      <ul>
        品牌旗艦
        <li>母親節嚴選</li>
        <li>dyson</li>
        <li>dysonhair</li>
        <li>三星旗艦</li>
        <li>石頭科技</li>
        <li>LG</li>
        <li>伊萊克斯</li>
        <li>飛利浦</li>
        <li>BOSE旗艦</li>
        <li>Bosch</li>
        <li>FUJI</li>
        <li>輝葉</li>
        <li>Nespresso</li>
        <li>雀巢</li>
        <li>小米</li>
      </ul>
      <ul>
        相關分類
        <li>冷暖空調</li>
        <li>液晶螢幕</li>
        <li>洗/乾衣機</li>
        <li>冰箱</li>
        <li>電風扇</li>
        <li>除濕機</li>
        <li>清淨機</li>
        <li>投影機</li>
        <li>影音/劇院</li>
        <li>吸塵器</li>
        <li>掃地機</li>
        <li>美容美髮</li>
        <li>按摩家電</li>
        <li>食物調理</li>
        <li>料理電器</li>
        <li>電子鍋/電鍋</li>
        <li>烤箱/微波爐</li>
        <li>洗/烘碗機</li>
        <li>潔牙/健康</li>
        <li>電鬍刀</li>
        <li>咖啡機</li>
        <li>生活家電</li>
        <li>冷熱飲水</li>
        <li>音響</li>
        <li>除衛三機</li>
        <li>電暖器</li>
        <li>通訊/辦公</li>
        <li>南紡家電</li>
      </ul>
    </div>
    <div>
      <span>日用</span>
      <ul>
        品牌旗艦
        <li>舒潔</li>
        <li>幫寶適</li>
        <li>滿意寶寶</li>
        <li>白蘭/熊寶貝</li>
        <li>多芬/麗仕</li>
        <li>五月花</li>
        <li>倍潔雅</li>
        <li>春風</li>
        <li>花仙子</li>
      </ul>
      <ul>
        相關分類
        <li>衛生紙</li>
        <li>嬰童紙尿褲</li>
        <li>衛生棉</li>
        <li>洗衣精</li>
        <li>家用清潔</li>
        <li>洗髮精</li>
        <li>牙膏牙刷漱口水</li>
        <li>沐浴乳/洗手乳</li>
        <li>臉部清潔</li>
        <li>掃除用品</li>
        <li>除濕除蟲</li>
        <li>濕紙巾</li>
        <li>成人紙尿褲</li>
        <li>防護抗菌</li>
        <li>天然有機</li>
        <li>進口洗沐</li>
        <li>箱購日用品</li>
        <li>商店街</li>
        <li>3M科技生活館</li>
        <li>泰國購物</li>
        <li>南紡生活</li>
      </ul>
    </div>
    <div>
      <span>母嬰</span>
      <ul>
        品牌旗艦
        <li>樂高®</li>
        <li>Combi</li>
        <li>LAVIDA</li>
      </ul>
      <ul>
        相關分類
        <li>婦幼</li>
        <li>嬰童</li>
        <li>推車汽座</li>
        <li>洗沐保養</li>
        <li>孕哺</li>
        <li>童裝</li>
        <li>玩具</li>
        <li>積木</li>
        <li>嬰童紙尿褲</li>
        <li>濕紙巾</li>
        <li>婦幼保健</li>
        <li>滴雞精</li>
        <li>奶粉</li>
        <li>婦幼保養</li>
        <li>桌遊</li>
        <li>模型公仔</li>
        <li>卡通館</li>
        <li>兒童家具</li>
      </ul>
    </div>
    <div>
      <span>食品</span>
      <ul>
        品牌旗艦
        <li>雀巢</li>
        <li>萬歲牌</li>
        <li>盛香珍</li>
        <li>M&M巧克力</li>
        <li>乖乖</li>
        <li>OREO</li>
        <li>黑貓</li>
        <li>鄰家鮮生</li>
      </ul>
      <ul>
        相關分類
        <li>PChome生鮮</li>
        <li>冷凍</li>
        <li>熟食</li>
        <li>蔬果甜點</li>
        <li>海鮮肉品</li>
        <li>團購</li>
        <li>票券</li>
        <li>PChome進口</li>
        <li>進口食品</li>
        <li>進口零食</li>
        <li>進口沖調</li>
        <li>進口食材</li>
        <li>飲料</li>
        <li>礦泉水</li>
        <li>零食</li>
        <li>堅果</li>
        <li>沖泡</li>
        <li>咖啡</li>
        <li>茶葉</li>
        <li>奶粉</li>
        <li>麥片</li>
        <li>生機</li>
        <li>米/食材</li>
        <li>泡麵</li>
        <li>油品</li>
        <li>罐頭</li>
        <li>箱購專區</li>
        <li>家好選物</li>
        <li>有賣商行</li>
        <li>立陶宛</li>
        <li>南紡食品</li>
        <li>泰國購物</li>
      </ul>
    </div>
    <div>
      <span>生活</span>
      <ul>
        品牌旗艦
        <li>MUJI無印良品</li>
        <li>樂高®</li>
        <li>BRITA</li>
        <li>康寧</li>
        <li>膳魔師</li>
        <li>樂扣樂扣</li>
        <li>Combi</li>
        <li>WMF</li>
      </ul>
      <ul>
        相關分類
        <li>鍋具</li>
        <li>餐廚</li>
        <li>烘焙用品</li>
        <li>餐具/保鮮盒</li>
        <li>隨行杯/保溫瓶</li>
        <li>咖啡/茶具</li>
        <li>婦幼</li>
        <li>嬰童</li>
        <li>推車/汽座</li>
        <li>孕哺</li>
        <li>童裝</li>
        <li>寢具/枕頭</li>
        <li>名寢</li>
        <li>床包</li>
        <li>床墊</li>
        <li>家飾</li>
        <li>玩具</li>
        <li>積木</li>
        <li>桌遊</li>
        <li>模型公仔</li>
        <li>衛浴用品</li>
        <li>衛浴設備</li>
        <li>卡通館</li>
        <li>有賣商行</li>
        <li>民視美鳳有約</li>
        <li>儲值</li>
        <li>綠色商品</li>
        <li>票券</li>
      </ul>
    </div>
    <div>
      <span>居家</span>
      <ul>
        品牌旗艦
        <li>BOSCH</li>
        <li>得利塗料</li>
        <li>H&D東稻家居</li>
        <li>ho!!好好生活</li>
        <li>IRIS</li>
        <li>OKAMURA</li>
        <li>3M生活</li>
        <li>未來實驗室</li>
        <li>飛利浦照明</li>
        <li>舞光照明</li>
        <li>生活工場</li>
      </ul>
      <ul>
        相關分類
        <li>電動工具</li>
        <li>修繕五金</li>
        <li>塗料地板</li>
        <li>電子鎖</li>
        <li>居家安全設備</li>
        <li>電腦椅</li>
        <li>層架</li>
        <li>收納用品</li>
        <li>品牌家具</li>
        <li>沙發/沙發床</li>
        <li>椅子/椅凳</li>
        <li>桌子/茶几</li>
        <li>床</li>
        <li>櫃子</li>
        <li>衣架/曬衣架</li>
        <li>兒童家具</li>
        <li>文具用品</li>
        <li>辦公用品</li>
        <li>園藝植栽</li>
        <li>燈管燈泡</li>
        <li>燈飾</li>
        <li>開運</li>
        <li>企業批發採購</li>
      </ul>
    </div>
    <div>
      <span>休閒</span>
      <ul>
        品牌旗艦
        <li>GARMIN</li>
        <li>TheNorthFace</li>
        <li>Mizuno</li>
        <li>NewBalance</li>
        <li>PUMA</li>
        <li>Asics</li>
        <li>米其林</li>
        <li>米其林精品</li>
        <li>車麗屋</li>
        <li>SportCity</li>
        <li>ABCMart</li>
        <li>SHIMANO</li>
        <li>Columbia</li>
        <li>歐都納</li>
        <li>毛孩嚴選</li>
      </ul>
      <ul>
        相關分類
        <li>露營</li>
        <li>登山</li>
        <li>機車</li>
        <li>機百</li>
        <li>汽百</li>
        <li>雨具</li>
        <li>健身</li>
        <li>單車</li>
        <li>運動服</li>
        <li>運動鞋</li>
        <li>智慧錶</li>
        <li>軍品</li>
        <li>貓食</li>
        <li>狗食</li>
        <li>貓砂/用品</li>
        <li>小動物</li>
        <li>機能服</li>
        <li>機能鞋</li>
        <li>球/護具</li>
        <li>按摩槍</li>
        <li>記錄器</li>
        <li>車電</li>
        <li>保險套</li>
        <li>情趣用品(女)</li>
        <li>情趣用品(男)</li>
        <li>情趣職人</li>
        <li>有責商行</li>
        <li>Gogoro</li>
        <li>NEWERA</li>
        <li>勝利體育</li>
        <li>ASHGOLF</li>
        <li>南紡運動</li>
        <li>休閒/泳具</li>
        <li>輪胎</li>
        <li>瑜珈</li>
        <li>GoPrp</li>
      </ul>
    </div>
    <div>
      <span>保健</span>
      <ul>
        品牌旗艦
        <li>世界健康日</li>
        <li>亞培</li>
        <li>桂格</li>
        <li>大研生醫</li>
        <li>白蘭氏</li>
        <li>娘家</li>
        <li>善存挺立克補</li>
        <li>三得利</li>
        <li>美國ON</li>
        <li>補體素</li>
        <li>益富</li>
        <li>船井生醫</li>
        <li>葡萄王</li>
        <li>三多</li>
        <li>達摩本草</li>
        <li>利捷維</li>
        <li>永信</li>
        <li>悠活原力</li>
        <li>日落恩賜</li>
        <li>LAC</li>
        <li>DHC</li>
        <li>PChome保健</li>
      </ul>
      <ul>
        相關分類
        <li>維他命</li>
        <li>益生菌</li>
        <li>滴雞精</li>
        <li>機能保健</li>
        <li>窈窕保健</li>
        <li>男性保健</li>
        <li>美顏保健</li>
        <li>婦幼保健</li>
        <li>運動保健</li>
        <li>營養品</li>
        <li>醫療用品/器材</li>
        <li>醫療口罩</li>
        <li>銀髮族</li>
      </ul>
    </div>
    <div>
      <span>美妝</span>
      <ul>
        品牌旗艦
        <li>碧兒泉</li>
        <li>蘭芝</li>
        <li>寶拉珍選</li>
        <li>佳麗寶集團</li>
        <li>理膚寶水</li>
        <li>歐舒丹</li>
        <li>巴黎萊雅媚比琳</li>
        <li>施巴</li>
        <li>提提研</li>
        <li>妮維雅</li>
        <li>雅漾</li>
        <li>幕之恬廊</li>
        <li>DHC</li>
        <li>AHC</li>
        <li>KOSE</li>
        <li>CeraVe</li>
        <li>薇姿</li>
      </ul>
      <ul>
        相關分類
        <li>專櫃保養</li>
        <li>專櫃彩妝</li>
        <li>醫美保養</li>
        <li>開架保養</li>
        <li>韓系品牌</li>
        <li>日系美妝</li>
        <li>彩妝美甲</li>
        <li>沙龍髮品</li>
        <li>染髮造型</li>
        <li>香水</li>
        <li>手工香氛皂</li>
        <li>香氛美體</li>
        <li>精油擴香</li>
        <li>婦幼專區</li>
        <li>私密保養</li>
        <li>草本品牌</li>
        <li>男士保養</li>
        <li>美容工具</li>
        <li>天然系專家</li>
        <li>蔻蘿蘭</li>
        <li>南紡美妝</li>
        <li>艾夫美</li>
      </ul>
    </div>
    <div>
      <span>時尚</span>
      <ul>
        品牌旗艦
        <li>Levis</li>
        <li>G2000</li>
        <li>PORTER</li>
        <li>TUMI</li>
        <li>CASIO</li>
        <li>點晴品</li>
        <li>Timberland</li>
        <li>SKECHERS</li>
        <li>LANEW</li>
        <li>三花棉業</li>
        <li>曼黛瑪璉</li>
        <li>華歌爾</li>
        <li>EASYSHOP</li>
        <li>Aimerfeel</li>
        <li>ROXY</li>
        <li>MUJI無印良品</li>
      </ul>
      <ul>
        相關分類
        <li>精品包/配件</li>
        <li>瑞士錶/精品錶</li>
        <li>手錶</li>
        <li>專櫃行李箱</li>
        <li>行李箱</li>
        <li>旅行用品</li>
        <li>電腦包/商務包</li>
        <li>男包/皮夾</li>
        <li>女包/斜背包</li>
        <li>黃金/金飾</li>
        <li>鑽石</li>
        <li>飾品/配件</li>
        <li>眼鏡/墨鏡</li>
        <li>機能服飾</li>
        <li>休閒服飾</li>
        <li>男裝/女裝/西裝</li>
        <li>男鞋/女鞋</li>
        <li>鞋材</li>
        <li>男內著/褲/背心</li>
        <li>襪子</li>
        <li>內衣/內衣褲</li>
        <li>睡衣</li>
        <li>塑身/塑身衣褲</li>
        <li>泳裝</li>
        <li>情趣內衣</li>
        <li>泰國購物</li>
        <li>南紡時尚</li>
        <li>MiTCH</li>
      </ul>
    </div>
    <div><span>書店</span></div>
  </div>
</template>
