<template>
  <div>
    <div>
      <span>3C</span>
      <ul>
        品牌旗艦
        <li>SanDisk</li>
        <li>Seagate</li>
        <li>TP-Link</li>
        <li>創見</li>
        <li>三星儲存</li>
      </ul>
      <ul>
        相關分類
        <li>筆記電腦</li>
        <li>桌上電腦</li>
        <li>商用電腦</li>
        <li>DIY電腦</li>
        <li>LCD電腦</li>
        <li>電競螢幕</li>
        <li>網路</li>
        <li>視訊監控</li>
        <li>SSD</li>
        <li>外接硬碟/SSD</li>
        <li>內接硬碟</li>
        <li>網路硬碟</li>
        <li>CPU</li>
        <li>主機板</li>
        <li>顯示卡</li>
        <li>電源供應器</li>
        <li>電腦機殼</li>
        <li>記憶體</li>
        <li>記憶卡</li>
        <li>隨身碟</li>
        <li>UPS</li>
        <li>電腦擴充</li>
        <li>軟體</li>
        <li>耗材</li>
        <li>線材</li>
        <li>電競專區</li>
        <li>台灣精品</li>
        <li>企業專區</li>
        <li>清倉</li>
        <li>南紡3C</li>
        <li>露天</li>
      </ul>
      <span>所有3C</span>
    </div>
    <div>
      <span>周邊</span>
      <ul>
        品牌旗艦
        <li>Logitech/羅技</li>
        <li>Razer雷蛇</li>
        <li>HyperX</li>
        <li>微軟Office</li>
        <li>Marshall</li>
      </ul>
      <ul>
        相關分類
        <li>滑鼠</li>
        <li>鍵盤</li>
        <li>喇叭</li>
        <li>耳機/麥克風</li>
        <li>直播設備</li>
        <li>線材</li>
        <li>延長線</li>
        <li>USBHUB/周邊</li>
        <li>電競椅</li>
        <li>辦公椅</li>
        <li>手寫/繪圖板</li>
        <li>閱讀器</li>
        <li>電腦軟體</li>
        <li>下載/點數</li>
        <li>辦公設備</li>
        <li>營業設備</li>
        <li>辦公傢俱</li>
        <li>噴墨印表機</li>
        <li>雷射印表機</li>
        <li>墨水匣/標籤帶</li>
        <li>碳粉匣</li>
        <li>紙類</li>
        <li>商用列印</li>
        <li>充電/電池</li>
        <li>筆電周邊/配件</li>
        <li>光碟片/機</li>
        <li>三井3C</li>
        <li>電腦/商務包</li>
        <li>嚴選小舖</li>
      </ul>
      <span>所有周邊</span>
    </div>
    <div>
      <span>NB</span>
      <ul>
        品牌旗艦
        <li>Intel第13&12代</li>
        <li>筆記電腦</li>
        <li>ASUS華碩</li>
        <li>ACER宏碁</li>
        <li>HP惠普</li>
        <li>Lenovo聯想</li>
        <li>微軟Surface</li>
        <li>DELL戴爾</li>
        <li>其他品牌</li>
        <li>APPLE</li>
        <li>ASUSZenBook</li>
        <li>ThinkPad商務</li>
        <li>ROG潮流電競</li>
        <li>MSI微星電競</li>
        <li>技嘉電競</li>
        <li>RAZER電競</li>
        <li>HP電競</li>
        <li>LEGION電競</li>
      </ul>
      <ul>
        相關分類
        <li>特仕筆電</li>
        <li>商用筆電</li>
        <li>EVO輕薄筆電</li>
        <li>2in1/觸控筆電</li>
        <li>電競筆電</li>
        <li>NVIDIA創作專區</li>
        <li>MSI微星</li>
        <li>Mac周邊</li>
      </ul>
    </div>
    <div>通訊</div>
    <div>數位</div>
    <div>家電</div>
    <div>日用</div>
    <div>母嬰</div>
    <div>食品</div>
    <div>生活</div>
    <div>居家</div>
    <div>休閒</div>
    <div>保健</div>
    <div>美妝</div>
    <div>時尚</div>
    <div>書店</div>
  </div>
</template>
